-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE comment (
    comment_id character varying(10) DEFAULT nextval('comments_comment_id_seq'::regclass) PRIMARY KEY,
    comment_text character varying(10000),
    comment_date timestamp without time zone,
    post_id character varying(10) NOT NULL DEFAULT nextval('comments_post_id_seq'::regclass) REFERENCES post(post_id),
    subreddit_name character varying(100) REFERENCES subreddit(subreddit_name),
    comment_op character varying(100),
    num_upvotes integer,
    sentiment_score real,
    stock_symbols character varying(200)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX comments_pkey ON comment(comment_id text_ops);
