-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE stocktickdata (
    ts timestamp without time zone,
    stock_symbol character varying(10),
    low_price real,
    high_price real,
    open_price real,
    close_price real,
    volume integer,
    CONSTRAINT stocktickdata_pkey PRIMARY KEY (ts, stock_symbol)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX stocktickdata_pkey ON stocktickdata(ts timestamp_ops,stock_symbol text_ops);
