-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE subreddit (
    subreddit_name character varying(50) PRIMARY KEY,
    num_followers integer,
    overview character varying(5000)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX subreddit_pkey ON subreddit(subreddit_name text_ops);
