-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE post (
    post_id character varying(10) DEFAULT nextval('post_post_id_seq'::regclass) PRIMARY KEY,
    post_title character varying(1000),
    post_description character varying(40000),
    post_tag character varying(100),
    post_date timestamp without time zone,
    subreddit_name character varying(100) REFERENCES subreddit(subreddit_name),
    post_op character varying(100),
    num_upvotes integer,
    sentiment_score real,
    stock_symbols character varying(200)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX post_pkey ON post(post_id text_ops);
