version: '3'

services:
    sql_db:
        image: postgres
        container_name: db01
        environment:
            - POSTGRES_PASSWORD=411_wsb_tendies
            - POSTGRES_DB=wsb_tendies
        ports:
            - "5431:5432"
        expose:
            - "5432"

    nosql_db:
        image: mongo:latest
        container_name: db02
        environment:
            - MONGO_INITDB_DATABASE=wsb_tendies
        ports:
            - "27016:27017"
        expose:
            - "27017"

    nginx:
        image: nginx:latest
        container_name: ng01
        ports:
            - "10080:80"
        volumes:
            - ./src:/src
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - web

    web:
        build: .
        container_name: w01
        command: bash -c "sleep 5; python3 manage.py makemigrations && python3 manage.py migrate && gunicorn tendies.wsgi -b 0.0.0.0:3000"
        ports:
            - "3000:3000"
        depends_on:
            - sql_db
            - nosql_db
        expose:
            - "3000"
